---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - maintainer: "Fuel Essence <info@fuelessence.com>"
    builds:
      - "gosk"
    license: "Apache 2.0"
    formats:
      - "apk"
      - "deb"
    overrides:
      apk:
        dependencies:
          - "postgresql14-client"
      deb:
        dependencies:
          - "postgresql-client-14"
    bindir: "/usr/bin"
