excludes = [
  "*.pub",
  "*.lock",
  "*.bin",
  "*.gif",
  "*.jpg",
  "*.ttf",
  "*.png",
  "*.svg",
  ".gitignore",
  ".envrc",
]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettierd]
command = "prettierd"
options = ["--stdin-filepath"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.shfmt]
command = "shfmt"
options = [
  "-i",
  "2",  # indent 2
  "-s", # simplify the code
  "-w", # write back to the file
]
includes = ["*.sh"]

[formatter.toml]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]
