// build using `protoc --go_out=paths=source_relative:. .\nanomsg\messages.proto`

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: nanomsg/messages.proto

package nanomsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeaderSegments []string `protobuf:"bytes,1,rep,name=headerSegments,proto3" json:"headerSegments,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanomsg_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_nanomsg_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_nanomsg_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetHeaderSegments() []string {
	if x != nil {
		return x.HeaderSegments
	}
	return nil
}

type RawData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RawData) Reset() {
	*x = RawData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanomsg_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawData) ProtoMessage() {}

func (x *RawData) ProtoReflect() protoreflect.Message {
	mi := &file_nanomsg_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawData.ProtoReflect.Descriptor instead.
func (*RawData) Descriptor() ([]byte, []int) {
	return file_nanomsg_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RawData) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RawData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RawData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MappedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Context   string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Path      string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are assignable to Value:
	//	*MappedData_DoubleValue
	//	*MappedData_StringValue
	//	*MappedData_PositionValue
	//	*MappedData_LengthValue
	//	*MappedData_VesselDataValue
	Value isMappedData_Value `protobuf_oneof:"value"`
}

func (x *MappedData) Reset() {
	*x = MappedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanomsg_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedData) ProtoMessage() {}

func (x *MappedData) ProtoReflect() protoreflect.Message {
	mi := &file_nanomsg_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedData.ProtoReflect.Descriptor instead.
func (*MappedData) Descriptor() ([]byte, []int) {
	return file_nanomsg_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MappedData) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MappedData) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *MappedData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MappedData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (m *MappedData) GetValue() isMappedData_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *MappedData) GetDoubleValue() float64 {
	if x, ok := x.GetValue().(*MappedData_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *MappedData) GetStringValue() string {
	if x, ok := x.GetValue().(*MappedData_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *MappedData) GetPositionValue() *PositionValue {
	if x, ok := x.GetValue().(*MappedData_PositionValue); ok {
		return x.PositionValue
	}
	return nil
}

func (x *MappedData) GetLengthValue() *LengthValue {
	if x, ok := x.GetValue().(*MappedData_LengthValue); ok {
		return x.LengthValue
	}
	return nil
}

func (x *MappedData) GetVesselDataValue() *VesselDataValue {
	if x, ok := x.GetValue().(*MappedData_VesselDataValue); ok {
		return x.VesselDataValue
	}
	return nil
}

type isMappedData_Value interface {
	isMappedData_Value()
}

type MappedData_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=doubleValue,proto3,oneof"`
}

type MappedData_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=stringValue,proto3,oneof"`
}

type MappedData_PositionValue struct {
	PositionValue *PositionValue `protobuf:"bytes,7,opt,name=positionValue,proto3,oneof"`
}

type MappedData_LengthValue struct {
	LengthValue *LengthValue `protobuf:"bytes,8,opt,name=lengthValue,proto3,oneof"`
}

type MappedData_VesselDataValue struct {
	VesselDataValue *VesselDataValue `protobuf:"bytes,9,opt,name=vesselDataValue,proto3,oneof"`
}

func (*MappedData_DoubleValue) isMappedData_Value() {}

func (*MappedData_StringValue) isMappedData_Value() {}

func (*MappedData_PositionValue) isMappedData_Value() {}

func (*MappedData_LengthValue) isMappedData_Value() {}

func (*MappedData_VesselDataValue) isMappedData_Value() {}

type PositionValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  *float64 `protobuf:"fixed64,1,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude *float64 `protobuf:"fixed64,2,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Altitude  *float64 `protobuf:"fixed64,3,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`
}

func (x *PositionValue) Reset() {
	*x = PositionValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanomsg_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionValue) ProtoMessage() {}

func (x *PositionValue) ProtoReflect() protoreflect.Message {
	mi := &file_nanomsg_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionValue.ProtoReflect.Descriptor instead.
func (*PositionValue) Descriptor() ([]byte, []int) {
	return file_nanomsg_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PositionValue) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *PositionValue) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *PositionValue) GetAltitude() float64 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

type LengthValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Overall   *float64 `protobuf:"fixed64,1,opt,name=overall,proto3,oneof" json:"overall,omitempty"`
	Hull      *float64 `protobuf:"fixed64,2,opt,name=hull,proto3,oneof" json:"hull,omitempty"`
	Waterline *float64 `protobuf:"fixed64,3,opt,name=waterline,proto3,oneof" json:"waterline,omitempty"`
}

func (x *LengthValue) Reset() {
	*x = LengthValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanomsg_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LengthValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LengthValue) ProtoMessage() {}

func (x *LengthValue) ProtoReflect() protoreflect.Message {
	mi := &file_nanomsg_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LengthValue.ProtoReflect.Descriptor instead.
func (*LengthValue) Descriptor() ([]byte, []int) {
	return file_nanomsg_messages_proto_rawDescGZIP(), []int{4}
}

func (x *LengthValue) GetOverall() float64 {
	if x != nil && x.Overall != nil {
		return *x.Overall
	}
	return 0
}

func (x *LengthValue) GetHull() float64 {
	if x != nil && x.Hull != nil {
		return *x.Hull
	}
	return 0
}

func (x *LengthValue) GetWaterline() float64 {
	if x != nil && x.Waterline != nil {
		return *x.Waterline
	}
	return 0
}

type VesselDataValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmsi *uint32 `protobuf:"varint,1,opt,name=mmsi,proto3,oneof" json:"mmsi,omitempty"`
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *VesselDataValue) Reset() {
	*x = VesselDataValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanomsg_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VesselDataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VesselDataValue) ProtoMessage() {}

func (x *VesselDataValue) ProtoReflect() protoreflect.Message {
	mi := &file_nanomsg_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VesselDataValue.ProtoReflect.Descriptor instead.
func (*VesselDataValue) Descriptor() ([]byte, []int) {
	return file_nanomsg_messages_proto_rawDescGZIP(), []int{5}
}

func (x *VesselDataValue) GetMmsi() uint32 {
	if x != nil && x.Mmsi != nil {
		return *x.Mmsi
	}
	return 0
}

func (x *VesselDataValue) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_nanomsg_messages_proto protoreflect.FileDescriptor

var file_nanomsg_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6e, 0x61, 0x6e, 0x6f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x06, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x7e, 0x0a, 0x07, 0x52,
	0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x8e, 0x03, 0x0a, 0x0a,
	0x4d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x56, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x48, 0x00, 0x52, 0x0f, 0x76, 0x65, 0x73, 0x73, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9c, 0x01, 0x0a,
	0x0d, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f,
	0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x00, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x21, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x0b,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6f,
	0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x07,
	0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x68, 0x75,
	0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x04, 0x68, 0x75, 0x6c, 0x6c,
	0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6c,
	0x69, 0x6e, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x61,
	0x6c, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x68, 0x75, 0x6c, 0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x77, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x55, 0x0a, 0x0f, 0x56, 0x65, 0x73,
	0x73, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x0a, 0x04,
	0x6d, 0x6d, 0x73, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6d,
	0x73, 0x69, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x6d, 0x6d, 0x73, 0x69, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x75, 0x6e, 0x6e, 0x69, 0x6b, 0x2f, 0x67, 0x6f, 0x73, 0x6b, 0x2f, 0x6e, 0x61, 0x6e, 0x6f, 0x6d,
	0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nanomsg_messages_proto_rawDescOnce sync.Once
	file_nanomsg_messages_proto_rawDescData = file_nanomsg_messages_proto_rawDesc
)

func file_nanomsg_messages_proto_rawDescGZIP() []byte {
	file_nanomsg_messages_proto_rawDescOnce.Do(func() {
		file_nanomsg_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_nanomsg_messages_proto_rawDescData)
	})
	return file_nanomsg_messages_proto_rawDescData
}

var file_nanomsg_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nanomsg_messages_proto_goTypes = []interface{}{
	(*Header)(nil),                // 0: Header
	(*RawData)(nil),               // 1: RawData
	(*MappedData)(nil),            // 2: MappedData
	(*PositionValue)(nil),         // 3: PositionValue
	(*LengthValue)(nil),           // 4: LengthValue
	(*VesselDataValue)(nil),       // 5: VesselDataValue
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_nanomsg_messages_proto_depIdxs = []int32{
	0, // 0: RawData.header:type_name -> Header
	6, // 1: RawData.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: MappedData.header:type_name -> Header
	6, // 3: MappedData.timestamp:type_name -> google.protobuf.Timestamp
	3, // 4: MappedData.positionValue:type_name -> PositionValue
	4, // 5: MappedData.lengthValue:type_name -> LengthValue
	5, // 6: MappedData.vesselDataValue:type_name -> VesselDataValue
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nanomsg_messages_proto_init() }
func file_nanomsg_messages_proto_init() {
	if File_nanomsg_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nanomsg_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanomsg_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanomsg_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanomsg_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanomsg_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LengthValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanomsg_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VesselDataValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nanomsg_messages_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*MappedData_DoubleValue)(nil),
		(*MappedData_StringValue)(nil),
		(*MappedData_PositionValue)(nil),
		(*MappedData_LengthValue)(nil),
		(*MappedData_VesselDataValue)(nil),
	}
	file_nanomsg_messages_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_nanomsg_messages_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_nanomsg_messages_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nanomsg_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nanomsg_messages_proto_goTypes,
		DependencyIndexes: file_nanomsg_messages_proto_depIdxs,
		MessageInfos:      file_nanomsg_messages_proto_msgTypes,
	}.Build()
	File_nanomsg_messages_proto = out.File
	file_nanomsg_messages_proto_rawDesc = nil
	file_nanomsg_messages_proto_goTypes = nil
	file_nanomsg_messages_proto_depIdxs = nil
}
