CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE; 

ALTER TABLE "raw_data"
ADD COLUMN "uuid" UUID NOT NULL DEFAULT uuid_nil();

ALTER TABLE "key_value_data"
ADD COLUMN "uuid" UUID NOT NULL DEFAULT uuid_nil();
