ALTER INDEX IF EXISTS key_value_data__time_idx RENAME TO mapped_data__time_idx;
ALTER INDEX IF EXISTS key_value_data_context_path_time_idx RENAME TO mapped_data_context_path_time_idx;
ALTER INDEX IF EXISTS key_value_data_path_time_idx RENAME TO mapped_data_path_time_idx;
