---
name: "Modbus simulator"  # name is used in the key of the collected data
protocol: "modbus"
# url of the connection, tcp:// and udp:// are supported for network
# connections, use file:///dev/ttyUSB0 for a serial device connection
url: "tcp://127.0.0.1:5020"
# when url is a network connection this determine to dial or listen for a
# connection [optional default is false]
listen: false
registerGroups:  # groups of registers that should be read in one request
  - slave: 1  # slave id
    # function code of the registers, 1 = coils, 2 = discrete inputs,
    # 3 = holding registers, 4 = input registers
    functionCode: 4
    address: 51300  # address of the first register to read, zero based
    # number of registers to read from address [optional default is 1]
    numberOfCoilsOrRegisters: 2
    # interval between consecutive reads in ns
    # [optional default is 1000000000 (1s)]
    pollingInterval: 500000000
  - slave: 1  # slave id
    # function code of the registers, 1 = coils, 2 = discrete inputs,
    # 3 = holding registers, 4 = input registers
    functionCode: 4
    address: 51440  # address of the first register to read, zero based
    # number of registers to read from address [optional default is 1]
    numberOfCoilsOrRegisters: 4
    # interval between consecutive reads in ns
    # [optional default is 1000000000 (1s)]
    pollingInterval: 500000000
    writeBeforeRead:
      slave: 1  # slave id
      # function code of the registers, 5 = write single coil,
      # 6 = write single holding register, 15 = multiple coils,
      # 16 = multiple holding registers
      functionCode: 6
      address: 101  # address of the first register to read, zero based
      # number of registers to read from address [optional default is 1]
      numberOfCoilsOrRegisters: 1
      values: [0, 128]  # array of bytes containing the value to write
      delay: "10000ms"
