// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson827bc575DecodeGithubComMunnikGoskMessage(in *jlexer.Lexer, out *Mapped) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "context":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Context = string(in.String())
			}
		case "origin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Origin = string(in.String())
			}
		case "updates":
			if in.IsNull() {
				in.Skip()
				out.Updates = nil
			} else {
				in.Delim('[')
				if out.Updates == nil {
					if !in.IsDelim(']') {
						out.Updates = make([]Update, 0, 0)
					} else {
						out.Updates = []Update{}
					}
				} else {
					out.Updates = (out.Updates)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Update
					easyjson827bc575DecodeGithubComMunnikGoskMessage1(in, &v1)
					out.Updates = append(out.Updates, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson827bc575EncodeGithubComMunnikGoskMessage(out *jwriter.Writer, in Mapped) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"context\":"
		out.RawString(prefix[1:])
		out.String(string(in.Context))
	}
	{
		const prefix string = ",\"origin\":"
		out.RawString(prefix)
		out.String(string(in.Origin))
	}
	{
		const prefix string = ",\"updates\":"
		out.RawString(prefix)
		if in.Updates == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Updates {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson827bc575EncodeGithubComMunnikGoskMessage1(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Mapped) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson827bc575EncodeGithubComMunnikGoskMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Mapped) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson827bc575EncodeGithubComMunnikGoskMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Mapped) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson827bc575DecodeGithubComMunnikGoskMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Mapped) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson827bc575DecodeGithubComMunnikGoskMessage(l, v)
}
func easyjson827bc575DecodeGithubComMunnikGoskMessage1(in *jlexer.Lexer, out *Update) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "source":
			easyjson827bc575DecodeGithubComMunnikGoskMessage2(in, &out.Source)
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Timestamp).UnmarshalJSON(data))
				}
			}
		case "values":
			if in.IsNull() {
				in.Skip()
				out.Values = nil
			} else {
				in.Delim('[')
				if out.Values == nil {
					if !in.IsDelim(']') {
						out.Values = make([]Value, 0, 2)
					} else {
						out.Values = []Value{}
					}
				} else {
					out.Values = (out.Values)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Value
					if in.IsNull() {
						in.Skip()
					} else {
						if data := in.Raw(); in.Ok() {
							in.AddError((v4).UnmarshalJSON(data))
						}
					}
					out.Values = append(out.Values, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson827bc575EncodeGithubComMunnikGoskMessage1(out *jwriter.Writer, in Update) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix[1:])
		easyjson827bc575EncodeGithubComMunnikGoskMessage2(out, in.Source)
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Raw((in.Timestamp).MarshalJSON())
	}
	{
		const prefix string = ",\"values\":"
		out.RawString(prefix)
		if in.Values == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Values {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjson827bc575EncodeGithubComMunnikGoskMessage3(out, v6)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson827bc575DecodeGithubComMunnikGoskMessage3(in *jlexer.Lexer, out *Value) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "value":
			if m, ok := out.Value.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Value.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Value = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson827bc575EncodeGithubComMunnikGoskMessage3(out *jwriter.Writer, in Value) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"path\":"
		out.RawString(prefix[1:])
		out.String(string(in.Path))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		if m, ok := in.Value.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Value.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Value))
		}
	}
	out.RawByte('}')
}
func easyjson827bc575DecodeGithubComMunnikGoskMessage2(in *jlexer.Lexer, out *Source) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.Uuid).UnmarshalText(data))
				}
			}
		case "transferUuid":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.TransferUuid).UnmarshalText(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson827bc575EncodeGithubComMunnikGoskMessage2(out *jwriter.Writer, in Source) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix[1:])
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix)
		out.RawText((in.Uuid).MarshalText())
	}
	{
		const prefix string = ",\"transferUuid\":"
		out.RawString(prefix)
		out.RawText((in.TransferUuid).MarshalText())
	}
	out.RawByte('}')
}
