// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package message

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Coefficient) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Magnitude":
			z.Magnitude, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Magnitude")
				return
			}
		case "Phase":
			z.Phase, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Phase")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Coefficient) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Magnitude"
	err = en.Append(0x82, 0xa9, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x74, 0x75, 0x64, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Magnitude)
	if err != nil {
		err = msgp.WrapError(err, "Magnitude")
		return
	}
	// write "Phase"
	err = en.Append(0xa5, 0x50, 0x68, 0x61, 0x73, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Phase)
	if err != nil {
		err = msgp.WrapError(err, "Phase")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Coefficient) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Magnitude"
	o = append(o, 0x82, 0xa9, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x74, 0x75, 0x64, 0x65)
	o = msgp.AppendFloat64(o, z.Magnitude)
	// string "Phase"
	o = append(o, 0xa5, 0x50, 0x68, 0x61, 0x73, 0x65)
	o = msgp.AppendFloat64(o, z.Phase)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Coefficient) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Magnitude":
			z.Magnitude, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Magnitude")
				return
			}
		case "Phase":
			z.Phase, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Phase")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Coefficient) Msgsize() (s int) {
	s = 1 + 10 + msgp.Float64Size + 6 + msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Draft) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Current":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Current")
					return
				}
				z.Current = nil
			} else {
				if z.Current == nil {
					z.Current = new(float64)
				}
				*z.Current, err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "Current")
					return
				}
			}
		case "CurrentPort":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "CurrentPort")
				return
			}
			if cap(z.CurrentPort) >= int(zb0002) {
				z.CurrentPort = (z.CurrentPort)[:zb0002]
			} else {
				z.CurrentPort = make([]float64, zb0002)
			}
			for za0001 := range z.CurrentPort {
				z.CurrentPort[za0001], err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "CurrentPort", za0001)
					return
				}
			}
		case "CurrentStarboard":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "CurrentStarboard")
				return
			}
			if cap(z.CurrentStarboard) >= int(zb0003) {
				z.CurrentStarboard = (z.CurrentStarboard)[:zb0003]
			} else {
				z.CurrentStarboard = make([]float64, zb0003)
			}
			for za0002 := range z.CurrentStarboard {
				z.CurrentStarboard[za0002], err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "CurrentStarboard", za0002)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Draft) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Current"
	err = en.Append(0x83, 0xa7, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	if z.Current == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteFloat64(*z.Current)
		if err != nil {
			err = msgp.WrapError(err, "Current")
			return
		}
	}
	// write "CurrentPort"
	err = en.Append(0xab, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.CurrentPort)))
	if err != nil {
		err = msgp.WrapError(err, "CurrentPort")
		return
	}
	for za0001 := range z.CurrentPort {
		err = en.WriteFloat64(z.CurrentPort[za0001])
		if err != nil {
			err = msgp.WrapError(err, "CurrentPort", za0001)
			return
		}
	}
	// write "CurrentStarboard"
	err = en.Append(0xb0, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.CurrentStarboard)))
	if err != nil {
		err = msgp.WrapError(err, "CurrentStarboard")
		return
	}
	for za0002 := range z.CurrentStarboard {
		err = en.WriteFloat64(z.CurrentStarboard[za0002])
		if err != nil {
			err = msgp.WrapError(err, "CurrentStarboard", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Draft) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Current"
	o = append(o, 0x83, 0xa7, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74)
	if z.Current == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendFloat64(o, *z.Current)
	}
	// string "CurrentPort"
	o = append(o, 0xab, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74)
	o = msgp.AppendArrayHeader(o, uint32(len(z.CurrentPort)))
	for za0001 := range z.CurrentPort {
		o = msgp.AppendFloat64(o, z.CurrentPort[za0001])
	}
	// string "CurrentStarboard"
	o = append(o, 0xb0, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64)
	o = msgp.AppendArrayHeader(o, uint32(len(z.CurrentStarboard)))
	for za0002 := range z.CurrentStarboard {
		o = msgp.AppendFloat64(o, z.CurrentStarboard[za0002])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Draft) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Current":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Current = nil
			} else {
				if z.Current == nil {
					z.Current = new(float64)
				}
				*z.Current, bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Current")
					return
				}
			}
		case "CurrentPort":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CurrentPort")
				return
			}
			if cap(z.CurrentPort) >= int(zb0002) {
				z.CurrentPort = (z.CurrentPort)[:zb0002]
			} else {
				z.CurrentPort = make([]float64, zb0002)
			}
			for za0001 := range z.CurrentPort {
				z.CurrentPort[za0001], bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CurrentPort", za0001)
					return
				}
			}
		case "CurrentStarboard":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CurrentStarboard")
				return
			}
			if cap(z.CurrentStarboard) >= int(zb0003) {
				z.CurrentStarboard = (z.CurrentStarboard)[:zb0003]
			} else {
				z.CurrentStarboard = make([]float64, zb0003)
			}
			for za0002 := range z.CurrentStarboard {
				z.CurrentStarboard[za0002], bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CurrentStarboard", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Draft) Msgsize() (s int) {
	s = 1 + 8
	if z.Current == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Float64Size
	}
	s += 12 + msgp.ArrayHeaderSize + (len(z.CurrentPort) * (msgp.Float64Size)) + 17 + msgp.ArrayHeaderSize + (len(z.CurrentStarboard) * (msgp.Float64Size))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Length) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Overall":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Overall")
					return
				}
				z.Overall = nil
			} else {
				if z.Overall == nil {
					z.Overall = new(float64)
				}
				*z.Overall, err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "Overall")
					return
				}
			}
		case "Hull":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Hull")
					return
				}
				z.Hull = nil
			} else {
				if z.Hull == nil {
					z.Hull = new(float64)
				}
				*z.Hull, err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "Hull")
					return
				}
			}
		case "Waterline":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Waterline")
					return
				}
				z.Waterline = nil
			} else {
				if z.Waterline == nil {
					z.Waterline = new(float64)
				}
				*z.Waterline, err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "Waterline")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Length) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Overall"
	err = en.Append(0x83, 0xa7, 0x4f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c)
	if err != nil {
		return
	}
	if z.Overall == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteFloat64(*z.Overall)
		if err != nil {
			err = msgp.WrapError(err, "Overall")
			return
		}
	}
	// write "Hull"
	err = en.Append(0xa4, 0x48, 0x75, 0x6c, 0x6c)
	if err != nil {
		return
	}
	if z.Hull == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteFloat64(*z.Hull)
		if err != nil {
			err = msgp.WrapError(err, "Hull")
			return
		}
	}
	// write "Waterline"
	err = en.Append(0xa9, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x65)
	if err != nil {
		return
	}
	if z.Waterline == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteFloat64(*z.Waterline)
		if err != nil {
			err = msgp.WrapError(err, "Waterline")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Length) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Overall"
	o = append(o, 0x83, 0xa7, 0x4f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c)
	if z.Overall == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendFloat64(o, *z.Overall)
	}
	// string "Hull"
	o = append(o, 0xa4, 0x48, 0x75, 0x6c, 0x6c)
	if z.Hull == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendFloat64(o, *z.Hull)
	}
	// string "Waterline"
	o = append(o, 0xa9, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x65)
	if z.Waterline == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendFloat64(o, *z.Waterline)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Length) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Overall":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Overall = nil
			} else {
				if z.Overall == nil {
					z.Overall = new(float64)
				}
				*z.Overall, bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Overall")
					return
				}
			}
		case "Hull":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Hull = nil
			} else {
				if z.Hull == nil {
					z.Hull = new(float64)
				}
				*z.Hull, bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Hull")
					return
				}
			}
		case "Waterline":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Waterline = nil
			} else {
				if z.Waterline == nil {
					z.Waterline = new(float64)
				}
				*z.Waterline, bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Waterline")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Length) Msgsize() (s int) {
	s = 1 + 8
	if z.Overall == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Float64Size
	}
	s += 5
	if z.Hull == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Float64Size
	}
	s += 10
	if z.Waterline == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Float64Size
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Notification) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "State":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = nil
			} else {
				if z.State == nil {
					z.State = new(string)
				}
				*z.State, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
			}
		case "Method":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Method")
				return
			}
			if cap(z.Method) >= int(zb0002) {
				z.Method = (z.Method)[:zb0002]
			} else {
				z.Method = make([]string, zb0002)
			}
			for za0001 := range z.Method {
				z.Method[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Method", za0001)
					return
				}
			}
		case "Message":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Message")
					return
				}
				z.Message = nil
			} else {
				if z.Message == nil {
					z.Message = new(string)
				}
				*z.Message, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Message")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Notification) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "State"
	err = en.Append(0x83, 0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	if z.State == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.State)
		if err != nil {
			err = msgp.WrapError(err, "State")
			return
		}
	}
	// write "Method"
	err = en.Append(0xa6, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Method)))
	if err != nil {
		err = msgp.WrapError(err, "Method")
		return
	}
	for za0001 := range z.Method {
		err = en.WriteString(z.Method[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Method", za0001)
			return
		}
	}
	// write "Message"
	err = en.Append(0xa7, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
	if err != nil {
		return
	}
	if z.Message == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.Message)
		if err != nil {
			err = msgp.WrapError(err, "Message")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Notification) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "State"
	o = append(o, 0x83, 0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	if z.State == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.State)
	}
	// string "Method"
	o = append(o, 0xa6, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Method)))
	for za0001 := range z.Method {
		o = msgp.AppendString(o, z.Method[za0001])
	}
	// string "Message"
	o = append(o, 0xa7, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
	if z.Message == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.Message)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Notification) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "State":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.State = nil
			} else {
				if z.State == nil {
					z.State = new(string)
				}
				*z.State, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
			}
		case "Method":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Method")
				return
			}
			if cap(z.Method) >= int(zb0002) {
				z.Method = (z.Method)[:zb0002]
			} else {
				z.Method = make([]string, zb0002)
			}
			for za0001 := range z.Method {
				z.Method[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Method", za0001)
					return
				}
			}
		case "Message":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Message = nil
			} else {
				if z.Message == nil {
					z.Message = new(string)
				}
				*z.Message, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Message")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Notification) Msgsize() (s int) {
	s = 1 + 6
	if z.State == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.State)
	}
	s += 7 + msgp.ArrayHeaderSize
	for za0001 := range z.Method {
		s += msgp.StringPrefixSize + len(z.Method[za0001])
	}
	s += 8
	if z.Message == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.Message)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Position) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Altitude":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Altitude")
					return
				}
				z.Altitude = nil
			} else {
				if z.Altitude == nil {
					z.Altitude = new(float64)
				}
				*z.Altitude, err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "Altitude")
					return
				}
			}
		case "Latitude":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Latitude")
					return
				}
				z.Latitude = nil
			} else {
				if z.Latitude == nil {
					z.Latitude = new(float64)
				}
				*z.Latitude, err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "Latitude")
					return
				}
			}
		case "Longitude":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Longitude")
					return
				}
				z.Longitude = nil
			} else {
				if z.Longitude == nil {
					z.Longitude = new(float64)
				}
				*z.Longitude, err = dc.ReadFloat64()
				if err != nil {
					err = msgp.WrapError(err, "Longitude")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Position) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Altitude"
	err = en.Append(0x83, 0xa8, 0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65)
	if err != nil {
		return
	}
	if z.Altitude == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteFloat64(*z.Altitude)
		if err != nil {
			err = msgp.WrapError(err, "Altitude")
			return
		}
	}
	// write "Latitude"
	err = en.Append(0xa8, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65)
	if err != nil {
		return
	}
	if z.Latitude == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteFloat64(*z.Latitude)
		if err != nil {
			err = msgp.WrapError(err, "Latitude")
			return
		}
	}
	// write "Longitude"
	err = en.Append(0xa9, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65)
	if err != nil {
		return
	}
	if z.Longitude == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteFloat64(*z.Longitude)
		if err != nil {
			err = msgp.WrapError(err, "Longitude")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Position) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Altitude"
	o = append(o, 0x83, 0xa8, 0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65)
	if z.Altitude == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendFloat64(o, *z.Altitude)
	}
	// string "Latitude"
	o = append(o, 0xa8, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65)
	if z.Latitude == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendFloat64(o, *z.Latitude)
	}
	// string "Longitude"
	o = append(o, 0xa9, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65)
	if z.Longitude == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendFloat64(o, *z.Longitude)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Position) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Altitude":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Altitude = nil
			} else {
				if z.Altitude == nil {
					z.Altitude = new(float64)
				}
				*z.Altitude, bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Altitude")
					return
				}
			}
		case "Latitude":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Latitude = nil
			} else {
				if z.Latitude == nil {
					z.Latitude = new(float64)
				}
				*z.Latitude, bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Latitude")
					return
				}
			}
		case "Longitude":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Longitude = nil
			} else {
				if z.Longitude == nil {
					z.Longitude = new(float64)
				}
				*z.Longitude, bts, err = msgp.ReadFloat64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Longitude")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Position) Msgsize() (s int) {
	s = 1 + 9
	if z.Altitude == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Float64Size
	}
	s += 9
	if z.Latitude == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Float64Size
	}
	s += 10
	if z.Longitude == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Float64Size
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Spectrum) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "NumberOfSamples":
			z.NumberOfSamples, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "NumberOfSamples")
				return
			}
		case "FrequencyStepSize":
			z.FrequencyStepSize, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "FrequencyStepSize")
				return
			}
		case "Duration":
			z.Duration, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Duration")
				return
			}
		case "Coefficients":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Coefficients")
				return
			}
			if cap(z.Coefficients) >= int(zb0002) {
				z.Coefficients = (z.Coefficients)[:zb0002]
			} else {
				z.Coefficients = make([]Coefficient, zb0002)
			}
			for za0001 := range z.Coefficients {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Coefficients", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Coefficients", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Magnitude":
						z.Coefficients[za0001].Magnitude, err = dc.ReadFloat64()
						if err != nil {
							err = msgp.WrapError(err, "Coefficients", za0001, "Magnitude")
							return
						}
					case "Phase":
						z.Coefficients[za0001].Phase, err = dc.ReadFloat64()
						if err != nil {
							err = msgp.WrapError(err, "Coefficients", za0001, "Phase")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Coefficients", za0001)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Spectrum) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "NumberOfSamples"
	err = en.Append(0x84, 0xaf, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.NumberOfSamples)
	if err != nil {
		err = msgp.WrapError(err, "NumberOfSamples")
		return
	}
	// write "FrequencyStepSize"
	err = en.Append(0xb1, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x74, 0x65, 0x70, 0x53, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.FrequencyStepSize)
	if err != nil {
		err = msgp.WrapError(err, "FrequencyStepSize")
		return
	}
	// write "Duration"
	err = en.Append(0xa8, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Duration)
	if err != nil {
		err = msgp.WrapError(err, "Duration")
		return
	}
	// write "Coefficients"
	err = en.Append(0xac, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Coefficients)))
	if err != nil {
		err = msgp.WrapError(err, "Coefficients")
		return
	}
	for za0001 := range z.Coefficients {
		// map header, size 2
		// write "Magnitude"
		err = en.Append(0x82, 0xa9, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x74, 0x75, 0x64, 0x65)
		if err != nil {
			return
		}
		err = en.WriteFloat64(z.Coefficients[za0001].Magnitude)
		if err != nil {
			err = msgp.WrapError(err, "Coefficients", za0001, "Magnitude")
			return
		}
		// write "Phase"
		err = en.Append(0xa5, 0x50, 0x68, 0x61, 0x73, 0x65)
		if err != nil {
			return
		}
		err = en.WriteFloat64(z.Coefficients[za0001].Phase)
		if err != nil {
			err = msgp.WrapError(err, "Coefficients", za0001, "Phase")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Spectrum) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "NumberOfSamples"
	o = append(o, 0x84, 0xaf, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	o = msgp.AppendInt(o, z.NumberOfSamples)
	// string "FrequencyStepSize"
	o = append(o, 0xb1, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x74, 0x65, 0x70, 0x53, 0x69, 0x7a, 0x65)
	o = msgp.AppendFloat64(o, z.FrequencyStepSize)
	// string "Duration"
	o = append(o, 0xa8, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendFloat64(o, z.Duration)
	// string "Coefficients"
	o = append(o, 0xac, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Coefficients)))
	for za0001 := range z.Coefficients {
		// map header, size 2
		// string "Magnitude"
		o = append(o, 0x82, 0xa9, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x74, 0x75, 0x64, 0x65)
		o = msgp.AppendFloat64(o, z.Coefficients[za0001].Magnitude)
		// string "Phase"
		o = append(o, 0xa5, 0x50, 0x68, 0x61, 0x73, 0x65)
		o = msgp.AppendFloat64(o, z.Coefficients[za0001].Phase)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Spectrum) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "NumberOfSamples":
			z.NumberOfSamples, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NumberOfSamples")
				return
			}
		case "FrequencyStepSize":
			z.FrequencyStepSize, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FrequencyStepSize")
				return
			}
		case "Duration":
			z.Duration, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Duration")
				return
			}
		case "Coefficients":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Coefficients")
				return
			}
			if cap(z.Coefficients) >= int(zb0002) {
				z.Coefficients = (z.Coefficients)[:zb0002]
			} else {
				z.Coefficients = make([]Coefficient, zb0002)
			}
			for za0001 := range z.Coefficients {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Coefficients", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Coefficients", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Magnitude":
						z.Coefficients[za0001].Magnitude, bts, err = msgp.ReadFloat64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Coefficients", za0001, "Magnitude")
							return
						}
					case "Phase":
						z.Coefficients[za0001].Phase, bts, err = msgp.ReadFloat64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Coefficients", za0001, "Phase")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Coefficients", za0001)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Spectrum) Msgsize() (s int) {
	s = 1 + 16 + msgp.IntSize + 18 + msgp.Float64Size + 9 + msgp.Float64Size + 13 + msgp.ArrayHeaderSize + (len(z.Coefficients) * (17 + msgp.Float64Size + msgp.Float64Size))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Vector3D) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "X":
			z.X, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "Y":
			z.Y, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		case "Z":
			z.Z, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Z")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Vector3D) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "X"
	err = en.Append(0x83, 0xa1, 0x58)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.X)
	if err != nil {
		err = msgp.WrapError(err, "X")
		return
	}
	// write "Y"
	err = en.Append(0xa1, 0x59)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Y)
	if err != nil {
		err = msgp.WrapError(err, "Y")
		return
	}
	// write "Z"
	err = en.Append(0xa1, 0x5a)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Z)
	if err != nil {
		err = msgp.WrapError(err, "Z")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Vector3D) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "X"
	o = append(o, 0x83, 0xa1, 0x58)
	o = msgp.AppendFloat64(o, z.X)
	// string "Y"
	o = append(o, 0xa1, 0x59)
	o = msgp.AppendFloat64(o, z.Y)
	// string "Z"
	o = append(o, 0xa1, 0x5a)
	o = msgp.AppendFloat64(o, z.Z)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Vector3D) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "X":
			z.X, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "Y":
			z.Y, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		case "Z":
			z.Z, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Z")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Vector3D) Msgsize() (s int) {
	s = 1 + 2 + msgp.Float64Size + 2 + msgp.Float64Size + 2 + msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *VesselInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "MMSI":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "MMSI")
					return
				}
				z.MMSI = nil
			} else {
				if z.MMSI == nil {
					z.MMSI = new(string)
				}
				*z.MMSI, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "MMSI")
					return
				}
			}
		case "Name":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Name")
					return
				}
				z.Name = nil
			} else {
				if z.Name == nil {
					z.Name = new(string)
				}
				*z.Name, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Name")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *VesselInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "MMSI"
	err = en.Append(0x82, 0xa4, 0x4d, 0x4d, 0x53, 0x49)
	if err != nil {
		return
	}
	if z.MMSI == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.MMSI)
		if err != nil {
			err = msgp.WrapError(err, "MMSI")
			return
		}
	}
	// write "Name"
	err = en.Append(0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	if z.Name == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.Name)
		if err != nil {
			err = msgp.WrapError(err, "Name")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *VesselInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "MMSI"
	o = append(o, 0x82, 0xa4, 0x4d, 0x4d, 0x53, 0x49)
	if z.MMSI == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.MMSI)
	}
	// string "Name"
	o = append(o, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if z.Name == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.Name)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *VesselInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "MMSI":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.MMSI = nil
			} else {
				if z.MMSI == nil {
					z.MMSI = new(string)
				}
				*z.MMSI, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MMSI")
					return
				}
			}
		case "Name":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Name = nil
			} else {
				if z.Name == nil {
					z.Name = new(string)
				}
				*z.Name, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Name")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *VesselInfo) Msgsize() (s int) {
	s = 1 + 5
	if z.MMSI == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.MMSI)
	}
	s += 5
	if z.Name == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.Name)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *VesselType) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Id")
					return
				}
				z.Id = nil
			} else {
				if z.Id == nil {
					z.Id = new(int)
				}
				*z.Id, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Id")
					return
				}
			}
		case "Description":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Description")
					return
				}
				z.Description = nil
			} else {
				if z.Description == nil {
					z.Description = new(string)
				}
				*z.Description, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Description")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *VesselType) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Id"
	err = en.Append(0x82, 0xa2, 0x49, 0x64)
	if err != nil {
		return
	}
	if z.Id == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt(*z.Id)
		if err != nil {
			err = msgp.WrapError(err, "Id")
			return
		}
	}
	// write "Description"
	err = en.Append(0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	if z.Description == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.Description)
		if err != nil {
			err = msgp.WrapError(err, "Description")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *VesselType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Id"
	o = append(o, 0x82, 0xa2, 0x49, 0x64)
	if z.Id == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt(o, *z.Id)
	}
	// string "Description"
	o = append(o, 0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	if z.Description == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.Description)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *VesselType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Id":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Id = nil
			} else {
				if z.Id == nil {
					z.Id = new(int)
				}
				*z.Id, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Id")
					return
				}
			}
		case "Description":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Description = nil
			} else {
				if z.Description == nil {
					z.Description = new(string)
				}
				*z.Description, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Description")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *VesselType) Msgsize() (s int) {
	s = 1 + 3
	if z.Id == nil {
		s += msgp.NilSize
	} else {
		s += msgp.IntSize
	}
	s += 12
	if z.Description == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.Description)
	}
	return
}
