// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson193538d8DecodeGithubComMunnikGoskMessage(in *jlexer.Lexer, out *rawWire) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "connector":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Connector = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uuid = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
				out.Value = nil
			} else {
				out.Value = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson193538d8EncodeGithubComMunnikGoskMessage(out *jwriter.Writer, in rawWire) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"connector\":"
		out.RawString(prefix[1:])
		out.String(string(in.Connector))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.String(string(in.Timestamp))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix)
		out.String(string(in.Uuid))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Value)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v rawWire) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson193538d8EncodeGithubComMunnikGoskMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v rawWire) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson193538d8EncodeGithubComMunnikGoskMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *rawWire) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson193538d8DecodeGithubComMunnikGoskMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *rawWire) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson193538d8DecodeGithubComMunnikGoskMessage(l, v)
}
