---
context: "vessels.urn:mrn:imo:mmsi:244770688" # if the data itself doesn't provide a context then this context is used
protocol: "modbus"
mappings:
  - slave: 1 # slave id
    functionCode: 4
    address: 0 # address of the first register to map
    numberOfCoilsOrRegisters: 4
    expression: "float64ToRegisters(propulsion_mainEnginePort_fuel_rate.Value)"
    path: "propulsion.mainEnginePort.fuel.rate"
  - slave: 1 # slave id
    functionCode: 4
    address: 4 # address of the first register to map
    numberOfCoilsOrRegisters: 4
    expression: "float64ToRegisters(propulsion_mainEngineStarboard_fuel_rate.Value)"
    path: "propulsion.mainEngineStarboard.fuel.rate"
