---
context: "vessels.urn:mrn:imo:mmsi:123456789"
protocol: "fft"
mappings:
  - path: "propulsion.mainEngine.drive.torque"
    spectrumPath: "propulsion.mainEngine.drive.torqueSpectrum"
    # at 2000 samples per second this is aboa bit over half a minute
    samplesChannelBitSize: 16
